import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../core/i18n/display_name.dart';
import '../../core/i18n/translations.dart';
import '../../data/database.dart';
import '../repositories/analytics/analytics_math.dart';

const exportColumnCount = 10;

/// Builds the 10-column export table (plan §9): date, translated type,
/// amount (2 decimals), currency, description, category as "Parent > Child",
/// payment method, event, project, comma-separated tags. Defaults are
/// resolved through `displayName` so exports read the same as the UI.
List<List<String>> buildExportRows({
  required List<Expense> expenses,
  required Map<String, Category> categoriesById,
  required Map<String, PaymentMethod> paymentMethodsById,
  required Map<String, Event> eventsById,
  required Map<String, Project> projectsById,
  required Map<String, List<String>> tagIdsByExpenseId,
  required Map<String, Tag> tagsById,
  required Translations translations,
}) {
  final dateFormat = DateFormat('yyyy-MM-dd');

  String categoryPath(String? categoryId) {
    if (categoryId == null) return '';
    final parts = <String>[];
    var current = categoriesById[categoryId];
    while (current != null) {
      parts.insert(0, displayNameFor(translations, name: current.name, isDefault: current.isDefault));
      current = current.parentId == null ? null : categoriesById[current.parentId];
    }
    return parts.join(' > ');
  }

  return [
    for (final e in expenses)
      [
        dateFormat.format(e.date),
        translations.t('expenses.type_${e.type}'),
        (e.amount / 100).toStringAsFixed(2),
        e.currency,
        e.description ?? '',
        categoryPath(e.categoryId),
        e.paymentMethodId == null
            ? ''
            : (paymentMethodsById[e.paymentMethodId] == null
                ? ''
                : displayNameFor(
                    translations,
                    name: paymentMethodsById[e.paymentMethodId]!.name,
                    isDefault: paymentMethodsById[e.paymentMethodId]!.isDefault,
                  )),
        e.eventId == null ? '' : (eventsById[e.eventId]?.name ?? ''),
        e.projectId == null ? '' : (projectsById[e.projectId]?.name ?? ''),
        (tagIdsByExpenseId[e.id] ?? const [])
            .map((tagId) => tagsById[tagId])
            .whereType<Tag>()
            .map((tag) => displayNameFor(translations, name: tag.name, isDefault: tag.isDefault))
            .join(', '),
      ],
  ];
}

/// Translation keys of the export column headers, in column order.
const _exportHeaderKeys = [
  'export.col_date',
  'export.col_type',
  'export.col_amount',
  'export.col_currency',
  'export.col_description',
  'export.col_category',
  'export.col_payment',
  'export.col_event',
  'export.col_project',
  'export.col_tags',
];

/// Column headers in the user's language.
List<String> buildExportHeader(Translations translations) =>
    [for (final key in _exportHeaderKeys) translations.t(key)];

/// Index of the amount column in an export row.
const _amountColumn = 2;

/// Field delimiter and decimal separator of a CSV export.
class CsvFormat {
  const CsvFormat({required this.delimiter, required this.decimalSeparator});

  final String delimiter;
  final String decimalSeparator;

  static const comma = CsvFormat(delimiter: ',', decimalSeparator: '.');
  static const semicolon = CsvFormat(delimiter: ';', decimalSeparator: ',');

  /// Spreadsheet convention of [locale]: English uses `,` + `.`; es/ca/fr/it
  /// use a decimal comma, so Excel there expects `;` as the field delimiter
  /// (otherwise the whole row lands in one column).
  factory CsvFormat.forLocale(String locale) => locale == 'en' ? comma : semicolon;
}

/// Columns holding machine-readable values (date, amount, currency). These are
/// generated by us, never free text, so they must NOT get the CSV-injection
/// guard prefix — that would corrupt them on re-import.
const _numericColumns = {0, 2, 3};

/// Leading characters a spreadsheet interprets as the start of a formula.
const _formulaStarters = {'=', '+', '-', '@'};

/// CSV with delimiter/quote/CR/LF escaping and a UTF-8 BOM so accented
/// characters survive when opened in Excel (plan §9). [format] sets the field
/// delimiter and the decimal separator of the amount column (see
/// [CsvFormat.forLocale]).
///
/// Free-text columns are also guarded against CSV injection: a field starting
/// with `= + - @` (optionally after tab/CR) is prefixed with a single quote so
/// Excel/Sheets treat it as text instead of an executable formula. The prefix
/// is only applied to text columns, never to date/amount/currency, so numeric
/// data survives a round-trip unchanged.
String buildExportCsv(
  List<List<String>> rows, {
  required List<String> header,
  CsvFormat format = CsvFormat.comma,
}) {
  String neutralize(String field, int column) {
    if (_numericColumns.contains(column) || field.isEmpty) return field;
    final firstMeaningful = field.replaceFirst(RegExp(r'^[\t\r ]+'), '');
    if (firstMeaningful.isEmpty) return field;
    return _formulaStarters.contains(firstMeaningful[0]) ? "'$field" : field;
  }

  String escape(String field) {
    if (field.contains(format.delimiter) || field.contains('"') || field.contains('\n') || field.contains('\r')) {
      return '"${field.replaceAll('"', '""')}"';
    }
    return field;
  }

  String encodeRow(List<String> row) {
    final cells = <String>[];
    for (var i = 0; i < row.length; i++) {
      final field = i == _amountColumn ? row[i].replaceAll('.', format.decimalSeparator) : row[i];
      cells.add(escape(neutralize(field, i)));
    }
    return cells.join(format.delimiter);
  }

  final buffer = StringBuffer('﻿');
  buffer.writeln(header.map(escape).join(format.delimiter));
  for (final row in rows) {
    buffer.writeln(encodeRow(row));
  }
  return buffer.toString();
}

Uint8List encodeCsvUtf8(String csv) => Uint8List.fromList(utf8.encode(csv));

/// Totals rows appended to the PDF table, shaped like export rows: one
/// "TOTAL" row per transaction type present in [expenses] (in the order
/// expense, income, refund, ahorro), then the net balance
/// (income − spent − savings, as defined in analytics_math).
List<List<String>> buildExportTotals({
  required List<Expense> expenses,
  required Translations translations,
}) {
  if (expenses.isEmpty) return const [];
  final currency = expenses.first.currency;
  String amount(int cents) => (cents / 100).toStringAsFixed(2);
  List<String> row(String label, String type, int cents) =>
      [label, type, amount(cents), currency, for (var i = 4; i < exportColumnCount; i++) ''];

  final total = translations.t('analytics.total_label');
  final presentTypes = expenses.map((e) => e.type).toSet();
  final balance = sumOfType(expenses, 'income') - expenseOutflow(expenses) - savingsSetAside(expenses);
  return [
    for (final type in const ['expense', 'income', 'refund', 'ahorro'])
      if (presentTypes.contains(type)) row(total, translations.t('expenses.type_$type'), sumOfType(expenses, type)),
    row(translations.t('dashboard.net_balance'), '', balance),
  ];
}

/// Landscape PDF table with a header describing the exported range, followed
/// by the [totals] rows (see [buildExportTotals]) in bold.
///
/// Uses the bundled Inter font instead of the `pdf` package's default
/// Helvetica, which has no Unicode support — without this, accented
/// characters (á, ñ, ç...) in descriptions/names/tags render as tofu boxes.
Future<Uint8List> buildExportPdf(
  List<List<String>> rows, {
  required String rangeLabel,
  required List<String> header,
  required String title,
  List<List<String>> totals = const [],
}) async {
  final regularFont = pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-Regular.ttf'));
  final boldFont = pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-Bold.ttf'));

  final doc = pw.Document(theme: pw.ThemeData.withFont(base: regularFont, bold: boldFont));
  final totalsStyle = pw.TextStyle(font: boldFont, fontWeight: pw.FontWeight.bold, fontSize: 8);
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4.landscape,
      build: (context) => [
        pw.Header(text: '$title - $rangeLabel'),
        pw.TableHelper.fromTextArray(
          headers: header,
          data: [...rows, ...totals],
          headerStyle: pw.TextStyle(font: boldFont, fontWeight: pw.FontWeight.bold),
          cellStyle: pw.TextStyle(font: regularFont, fontSize: 8),
          // rowNum counts the header row, so totals start at rows.length + 1.
          textStyleBuilder: (_, _, rowNum) => rowNum > rows.length ? totalsStyle : null,
          cellAlignment: pw.Alignment.centerLeft,
        ),
      ],
    ),
  );
  return doc.save();
}
